#!/bin/bash

echo "🔧 Cloudflare DNS Configuration Fix for ytvanced.pro"
echo "=================================================="
echo ""
echo "Issue: Your root domain record might be misconfigured."
echo ""
echo "🔧 Required DNS Records Fix:"
echo "--------------------------------------------------"
echo "1. DELETE the current CNAME record for 'ytvanced.pro'"
echo "2. ADD a new CNAME record with these settings:"
echo "   - Type: CNAME"
echo "   - Name: @"
echo "   - Content: cname.vercel-dns.com"
echo "   - Proxy status: DNS only (gray cloud)"
echo ""
echo "3. Keep the existing www record:"
echo "   - Type: CNAME"
echo "   - Name: www"
echo "   - Content: cname.vercel-dns.com"
echo "   - Proxy status: DNS only (gray cloud)"
echo ""
echo "📋 Steps to fix in Cloudflare:"
echo "--------------------------------------------------"
echo "1. Login to your Cloudflare dashboard"
echo "2. Select the ytvanced.pro domain"
echo "3. Go to DNS settings"
echo "4. Delete the CNAME record for 'ytvanced.pro'"
echo "5. Add new CNAME record with '@' as the name"
echo "6. Save changes"
echo "7. Wait 5-15 minutes for DNS propagation"
echo ""
echo "✅ After making these changes, your website should be accessible at https://ytvanced.pro"