#!/bin/bash

echo "🔧 Hostinger Nameserver Update Guide for ytvanced.pro"
echo "=================================================="
echo ""

echo "📋 STEP 1: Login to Hostinger"
echo "----------------------------"
echo "1. Go to https://www.hostinger.com/login"
echo "2. Enter your email and password"
echo "3. Click 'Login'"
echo ""

echo "📋 STEP 2: Access Domain Management"
echo "----------------------------------"
echo "1. In your Hostinger dashboard, click on 'Domains'"
echo "2. Find 'ytvanced.pro' in your domain list"
echo "3. Click on the three dots next to the domain name"
echo "4. Select 'Manage'"
echo ""

echo "📋 STEP 3: Update Nameservers"
echo "----------------------------"
echo "1. In the domain management page, look for 'Nameservers' or 'DNS Management'"
echo "2. Select 'Custom Nameservers' (not 'Use default nameservers')"
echo "3. Enter these Cloudflare nameservers:"
echo "   Primary Nameserver: lakas.ns.cloudflare.com"
echo "   Secondary Nameserver: tori.ns.cloudflare.com"
echo "4. Click 'Save' or 'Update Nameservers'"
echo ""

echo "📋 STEP 4: Wait for Propagation"
echo "------------------------------"
echo "1. Nameserver propagation can take 4-24 hours"
echo "2. You can monitor progress with: ./monitor-nameservers.sh"
echo "3. When successful, 'dig +short NS ytvanced.pro' will show Cloudflare nameservers"
echo ""

echo "📋 STEP 5: After Nameserver Propagation"
echo "--------------------------------------"
echo "1. Log in to Cloudflare dashboard"
echo "2. Fix DNS records (delete A record, add correct CNAME records)"
echo "3. Add custom domain to Vercel dashboard"
echo ""

echo "✅ SUCCESS INDICATORS"
echo "-------------------"
echo "When everything is working correctly:"
echo "1. dig +short NS ytvanced.pro → lakas.ns.cloudflare.com and tori.ns.cloudflare.com"
echo "2. dig +short ytvanced.pro CNAME → cname.vercel-dns.com"
echo "3. https://ytvanced.pro shows your website (not Hostinger parking page)"
echo ""